version: '3.8'

services:
  epicfy_storage:
    image: mariadb:10.5
    container_name: epicfy_storage
    platform: linux/amd64 
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=America/Sao_Paulo
    volumes:
      - ./src/config/migrations/:/docker-entrypoint-initdb.d/
    env_file: .env
    restart: always

  epicfy_backend:
    image: node:20-alpine
    container_name: epicfy_backend
    ports:
      - "${APP_PORT}:3000"
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    command: sh -c "yarn install && yarn dev"
    tty: true
    depends_on:
      - epicfy_storage
